name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.0.0
homepage: https://github.com/brianegan/chewie

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
#   video_player: ^2.0.0
#   ext_video_player: ^0.0.3
#   ext_video_player: ^0.0.6

  ext_video_player:
    git:
      url: https://github.com/azhar-rafiq/ext_video_player/
  wakelock: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter:
  uses-material-design: true
